import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Todo.module.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faTrashCan } from "@fortawesome/free-solid-svg-icons";

const inter = Inter({ subsets: ["latin"] });

const checked = item => {
  const li = item.target.closest("li");
  let label = li.querySelector("label");
  let div = li.querySelector("#div-checked");

  label.style.textDecoration = "line-through";
  div.style.backgroundColor = "grey";
}

const deleted = item => {
  const li = item.target.closest("li");
  li.remove();
}

export default function Home() {
  return (
    <>
      <Head>
        <title>MYT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.first_section}>
          <h1>MYTodolist</h1>
          <div className={styles.adder}>
            <input type="text" />
            <button>Add</button>
          </div>

          <div className={styles.list}>
            <ul>
              <li onClick={checked}>
                <div id="div-checked">
                  <label>xfhxfffg</label>
                </div>
                <button onClick={deleted}>
                  <FontAwesomeIcon icon={faTrashCan} size="1x" color="black" />
                </button>
              </li>

              <li onClick={checked}>
                <div id="div-checked">
                  <label>xfhxffdxfdhfddfffffffffffffffffg</label>
                </div>
                <button onClick={deleted}>
                  <FontAwesomeIcon icon={faTrashCan} size="1x" color="black" />
                </button>
              </li>

              <li onClick={checked}>
                <div id="div-checked">
                  <label>xfhxffdxfdhfdggggffffffffffffffffffffffffffffffg</label>
                </div>
                <button onClick={deleted}>
                  <FontAwesomeIcon icon={faTrashCan} size="1x" color="black" />
                </button>
              </li>
            </ul>
          </div>
        </div>
      </main>
    </>
  );
}
